### PR TITLE
Trump suit in the second phase 

### PR DESCRIPTION
**Pull request by hasan-sh**
Currently while testing, in visual mode, we cannot see what the trump suit is; see the screenshots. This PR adds that piece.
Previously:
no_suit

Now: 
with_suit

### CODE REVIEW

**Comment by PaulUrsulean** [comment]
Great idea. It would be nice if we could show this information either throughout the whole game (e.g. on the top bar in both phases, supplementary to the visual cue in the 1st phase), or somehow integrate it in the 2nd phase in a way that is consistent with the 1st phase (e.g. placing the text below the stock so that it becomes visible when it is exhausted, or maybe even leaving a transparent copy of the trump card behind when it is drawn). All of these options would avoid users conditionally having to look to different places on the screen for the same information depending on the phase of the game.

What do you think?

**Comment by hasan-sh** [comment]
@PaulUrsulean thanks for the swift response! Your suggestions struggled me as well in the beginning. Then i thought: only in the second phase and in the middle-right of the screen, it would be sufficient and visible. But of course that's (only) for me! 
I actually like your first idea; having it always visible next to the other buttons. In that case, nobody would wonder what the trump suit is. 
You agree?

**Comment by hasan-sh** [comment]
@PaulUrsulean perhaps like this?!
trump

**Comment by PaulUrsulean** [comment]
Looks fine, will take a look over the weekend.

**Comment by miselico** [comment]
@PaulUrsulean  we already took the previous PR into https://github.com/intelligent-systems-course/schnapsen

I am also pushing a few other minor fixes. Perhaps we can later on cherry-pick them into one repo?

**Comment by PaulUrsulean** [comment]
@miselico Sure, let me know by email if you would like to have a short call at some point to discuss this and other organizational matters regarding the repo.

**Pull request closed without merging**
